/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.apis

import com.fasterxml.jackson.annotation.JsonProperty

import org.springframework.web.client.RestClient
import org.springframework.web.client.RestClientResponseException

import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
import org.springframework.http.ResponseEntity
import org.springframework.http.MediaType


import com.midaz.client.onboarding.models.CreateLedgerInput
import com.midaz.client.onboarding.models.Error
import com.midaz.client.onboarding.models.InlineResponse2001
import com.midaz.client.onboarding.models.Ledger
import com.midaz.client.onboarding.models.UpdateLedgerInput
import com.midaz.client.onboarding.infrastructure.*

class LedgersApi(client: RestClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(RestClient.builder()
        .baseUrl(baseUrl)
        .messageConverters { it.add(MappingJackson2HttpMessageConverter()) }
        .build()
    )

    /**
     * enum for parameter sortOrder
     */
    enum class SortOrderV1OrganizationsOrganizationIdLedgersGet(val value: kotlin.String) {
        @JsonProperty(value = "asc") asc("asc"),
        @JsonProperty(value = "desc") desc("desc")
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersGet(authorization: kotlin.String, organizationId: kotlin.String, xRequestId: kotlin.String? = null, metadata: kotlin.String? = null, limit: kotlin.Int? = 10, page: kotlin.Int? = 1, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersGet? = null): InlineResponse2001 {
        val result = v1OrganizationsOrganizationIdLedgersGetWithHttpInfo(authorization = authorization, organizationId = organizationId, xRequestId = xRequestId, metadata = metadata, limit = limit, page = page, startDate = startDate, endDate = endDate, sortOrder = sortOrder)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, xRequestId: kotlin.String? = null, metadata: kotlin.String? = null, limit: kotlin.Int? = 10, page: kotlin.Int? = 1, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersGet? = null): ResponseEntity<InlineResponse2001> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersGetRequestConfig(authorization = authorization, organizationId = organizationId, xRequestId = xRequestId, metadata = metadata, limit = limit, page = page, startDate = startDate, endDate = endDate, sortOrder = sortOrder)
        return request<Unit, InlineResponse2001>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, xRequestId: kotlin.String? = null, metadata: kotlin.String? = null, limit: kotlin.Int? = 10, page: kotlin.Int? = 1, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersGet? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (metadata != null) {
                    put("metadata", listOf(metadata.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (startDate != null) {
                    put("start_date", listOf(startDate.toString()))
                }
                if (endDate != null) {
                    put("end_date", listOf(endDate.toString()))
                }
                if (sortOrder != null) {
                    put("sort_order", listOf(sortOrder.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersIdDelete(authorization: kotlin.String, organizationId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null): kotlin.String {
        val result = v1OrganizationsOrganizationIdLedgersIdDeleteWithHttpInfo(authorization = authorization, organizationId = organizationId, id = id, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersIdDeleteWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<kotlin.String> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersIdDeleteRequestConfig(authorization = authorization, organizationId = organizationId, id = id, xRequestId = xRequestId)
        return request<Unit, kotlin.String>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersIdDeleteRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "*/*"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "id" to id,
        )

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/organizations/{organization_id}/ledgers/{id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersIdGet(authorization: kotlin.String, organizationId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null): Ledger {
        val result = v1OrganizationsOrganizationIdLedgersIdGetWithHttpInfo(authorization = authorization, organizationId = organizationId, id = id, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersIdGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<Ledger> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersIdGetRequestConfig(authorization = authorization, organizationId = organizationId, id = id, xRequestId = xRequestId)
        return request<Unit, Ledger>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersIdGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "id" to id,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersIdPatch(authorization: kotlin.String, organizationId: kotlin.String, id: kotlin.String, ledger: UpdateLedgerInput, xRequestId: kotlin.String? = null): Ledger {
        val result = v1OrganizationsOrganizationIdLedgersIdPatchWithHttpInfo(authorization = authorization, organizationId = organizationId, id = id, ledger = ledger, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersIdPatchWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, id: kotlin.String, ledger: UpdateLedgerInput, xRequestId: kotlin.String? = null): ResponseEntity<Ledger> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersIdPatchRequestConfig(authorization = authorization, organizationId = organizationId, id = id, ledger = ledger, xRequestId = xRequestId)
        return request<UpdateLedgerInput, Ledger>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersIdPatchRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, id: kotlin.String, ledger: UpdateLedgerInput, xRequestId: kotlin.String? = null) : RequestConfig<UpdateLedgerInput> {
        val localVariableBody = ledger
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "id" to id,
        )

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/organizations/{organization_id}/ledgers/{id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersMetricsCountHead(authorization: kotlin.String, organizationId: kotlin.String, xRequestId: kotlin.String? = null): kotlin.String {
        val result = v1OrganizationsOrganizationIdLedgersMetricsCountHeadWithHttpInfo(authorization = authorization, organizationId = organizationId, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersMetricsCountHeadWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<kotlin.String> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersMetricsCountHeadRequestConfig(authorization = authorization, organizationId = organizationId, xRequestId = xRequestId)
        return request<Unit, kotlin.String>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersMetricsCountHeadRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "*/*"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
        )

        return RequestConfig(
            method = RequestMethod.HEAD,
            path = "/v1/organizations/{organization_id}/ledgers/metrics/count",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersPost(authorization: kotlin.String, organizationId: kotlin.String, ledger: CreateLedgerInput, xRequestId: kotlin.String? = null): Ledger {
        val result = v1OrganizationsOrganizationIdLedgersPostWithHttpInfo(authorization = authorization, organizationId = organizationId, ledger = ledger, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersPostWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledger: CreateLedgerInput, xRequestId: kotlin.String? = null): ResponseEntity<Ledger> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersPostRequestConfig(authorization = authorization, organizationId = organizationId, ledger = ledger, xRequestId = xRequestId)
        return request<CreateLedgerInput, Ledger>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersPostRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledger: CreateLedgerInput, xRequestId: kotlin.String? = null) : RequestConfig<CreateLedgerInput> {
        val localVariableBody = ledger
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/organizations/{organization_id}/ledgers",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

}
