/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.apis

import com.fasterxml.jackson.annotation.JsonProperty

import org.springframework.web.client.RestClient
import org.springframework.web.client.RestClientResponseException

import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
import org.springframework.http.ResponseEntity
import org.springframework.http.MediaType


import com.midaz.client.onboarding.models.CreateSegmentInput
import com.midaz.client.onboarding.models.Error
import com.midaz.client.onboarding.models.InlineResponse2006
import com.midaz.client.onboarding.models.Segment
import com.midaz.client.onboarding.models.UpdateSegmentInput
import com.midaz.client.onboarding.infrastructure.*

class SegmentsApi(client: RestClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(RestClient.builder()
        .baseUrl(baseUrl)
        .messageConverters { it.add(MappingJackson2HttpMessageConverter()) }
        .build()
    )

    /**
     * enum for parameter sortOrder
     */
    enum class SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdSegmentsGet(val value: kotlin.String) {
        @JsonProperty(value = "asc") asc("asc"),
        @JsonProperty(value = "desc") desc("desc")
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, metadata: kotlin.String? = null, limit: kotlin.Int? = 10, page: kotlin.Int? = 1, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdSegmentsGet? = null): InlineResponse2006 {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, xRequestId = xRequestId, metadata = metadata, limit = limit, page = page, startDate = startDate, endDate = endDate, sortOrder = sortOrder)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, metadata: kotlin.String? = null, limit: kotlin.Int? = 10, page: kotlin.Int? = 1, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdSegmentsGet? = null): ResponseEntity<InlineResponse2006> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, xRequestId = xRequestId, metadata = metadata, limit = limit, page = page, startDate = startDate, endDate = endDate, sortOrder = sortOrder)
        return request<Unit, InlineResponse2006>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, metadata: kotlin.String? = null, limit: kotlin.Int? = 10, page: kotlin.Int? = 1, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdSegmentsGet? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (metadata != null) {
                    put("metadata", listOf(metadata.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (startDate != null) {
                    put("start_date", listOf(startDate.toString()))
                }
                if (endDate != null) {
                    put("end_date", listOf(endDate.toString()))
                }
                if (sortOrder != null) {
                    put("sort_order", listOf(sortOrder.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/segments",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdDelete(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null): Unit {
        v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdDeleteWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, id = id, xRequestId = xRequestId)
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdDeleteWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<Unit> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdDeleteRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, id = id, xRequestId = xRequestId)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdDeleteRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "*/*"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "id" to id,
        )

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/segments/{id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null): Segment {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, id = id, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<Segment> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, id = id, xRequestId = xRequestId)
        return request<Unit, Segment>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "id" to id,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/segments/{id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdPatch(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, segment: UpdateSegmentInput, xRequestId: kotlin.String? = null): Segment {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdPatchWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, id = id, segment = segment, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdPatchWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, segment: UpdateSegmentInput, xRequestId: kotlin.String? = null): ResponseEntity<Segment> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdPatchRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, id = id, segment = segment, xRequestId = xRequestId)
        return request<UpdateSegmentInput, Segment>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsIdPatchRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, segment: UpdateSegmentInput, xRequestId: kotlin.String? = null) : RequestConfig<UpdateSegmentInput> {
        val localVariableBody = segment
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "id" to id,
        )

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/segments/{id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsMetricsCountHead(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null): Unit {
        v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsMetricsCountHeadWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, xRequestId = xRequestId)
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsMetricsCountHeadWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<Unit> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsMetricsCountHeadRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, xRequestId = xRequestId)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsMetricsCountHeadRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "*/*"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
        )

        return RequestConfig(
            method = RequestMethod.HEAD,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/segments/metrics/count",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsPost(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, segment: CreateSegmentInput, xRequestId: kotlin.String? = null): Segment {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsPostWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, segment = segment, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsPostWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, segment: CreateSegmentInput, xRequestId: kotlin.String? = null): ResponseEntity<Segment> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsPostRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, segment = segment, xRequestId = xRequestId)
        return request<CreateSegmentInput, Segment>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdSegmentsPostRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, segment: CreateSegmentInput, xRequestId: kotlin.String? = null) : RequestConfig<CreateSegmentInput> {
        val localVariableBody = segment
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/segments",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

}
