/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Amount is the struct designed to represent the amount of an operation. Contains the value and scale (decimal places) of an operation amount.
 *
 * @param `value` The amount value in the smallest unit of the asset (e.g., cents) example: 1500 minimum: 0
 */


data class Amount (

    /* The amount value in the smallest unit of the asset (e.g., cents) example: 1500 minimum: 0 */
    @get:JsonProperty("value")
    val `value`: java.math.BigDecimal? = null

) {


}

