/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * AssetRate is a struct designed to store asset rate data. Represents a complete asset rate entity containing conversion information between two assets, including all system-generated fields.
 *
 * @param createdAt Timestamp when the asset rate was created example: 2021-01-01T00:00:00Z format: date-time
 * @param externalId External identifier for integration with third-party systems example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param from Source asset code example: USD minLength: 2 maxLength: 10
 * @param id Unique identifier for the asset rate example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param ledgerId Ledger containing this asset rate example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param metadata Additional custom attributes example: {\"provider\": \"Central Bank\", \"rateName\": \"Official Exchange Rate\"}
 * @param organizationId Organization that owns this asset rate example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param rate Conversion rate value example: 100
 * @param scale Decimal places for the rate example: 2 minimum: 0
 * @param source Source of rate information example: External System maxLength: 200
 * @param to Target asset code example: BRL minLength: 2 maxLength: 10
 * @param ttl Time-to-live in seconds example: 3600 minimum: 0
 * @param updatedAt Timestamp when the asset rate was last updated example: 2021-01-01T00:00:00Z format: date-time
 */


data class AssetRate (

    /* Timestamp when the asset rate was created example: 2021-01-01T00:00:00Z format: date-time */
    @get:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    /* External identifier for integration with third-party systems example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("externalId")
    val externalId: java.util.UUID? = null,

    /* Source asset code example: USD minLength: 2 maxLength: 10 */
    @get:JsonProperty("from")
    val from: kotlin.String? = null,

    /* Unique identifier for the asset rate example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("id")
    val id: java.util.UUID? = null,

    /* Ledger containing this asset rate example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("ledgerId")
    val ledgerId: java.util.UUID? = null,

    /* Additional custom attributes example: {\"provider\": \"Central Bank\", \"rateName\": \"Official Exchange Rate\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Organization that owns this asset rate example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("organizationId")
    val organizationId: java.util.UUID? = null,

    /* Conversion rate value example: 100 */
    @get:JsonProperty("rate")
    val rate: java.math.BigDecimal? = null,

    /* Decimal places for the rate example: 2 minimum: 0 */
    @get:JsonProperty("scale")
    val scale: java.math.BigDecimal? = null,

    /* Source of rate information example: External System maxLength: 200 */
    @get:JsonProperty("source")
    val source: kotlin.String? = null,

    /* Target asset code example: BRL minLength: 2 maxLength: 10 */
    @get:JsonProperty("to")
    val to: kotlin.String? = null,

    /* Time-to-live in seconds example: 3600 minimum: 0 */
    @get:JsonProperty("ttl")
    val ttl: kotlin.Int? = null,

    /* Timestamp when the asset rate was last updated example: 2021-01-01T00:00:00Z format: date-time */
    @get:JsonProperty("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

