/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Balance is the struct designed to represent the account balance. Contains available and on-hold amounts along with the scale (decimal places).
 *
 * @param available Amount available for transactions (in the smallest unit of asset) example: 1500 minimum: 0
 * @param onHold Amount on hold and unavailable for transactions (in the smallest unit of asset) example: 500 minimum: 0
 */


data class Balance (

    /* Amount available for transactions (in the smallest unit of asset) example: 1500 minimum: 0 */
    @get:JsonProperty("available")
    val available: java.math.BigDecimal? = null,

    /* Amount on hold and unavailable for transactions (in the smallest unit of asset) example: 500 minimum: 0 */
    @get:JsonProperty("onHold")
    val onHold: java.math.BigDecimal? = null

) {


}

