/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models

import com.midaz.client.transactions.models.CreateTransactionInflowSwaggerModelSend

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Schema for creating inflow transaction with the complete SendInflow operation structure defined inline
 *
 * @param chartOfAccountsGroupName Chart of accounts group name for accounting purposes example: FUNDING maxLength: 256
 * @param code Transaction code for reference example: TR12345 maxLength: 100
 * @param description Human-readable description of the transaction example: New Inflow Transaction maxLength: 256
 * @param metadata Additional custom attributes example: {\"reference\": \"TRANSACTION-001\", \"source\": \"api\"}
 * @param send 
 */


data class CreateTransactionInflowSwaggerModel (

    /* Chart of accounts group name for accounting purposes example: FUNDING maxLength: 256 */
    @get:JsonProperty("chartOfAccountsGroupName")
    val chartOfAccountsGroupName: kotlin.String? = null,

    /* Transaction code for reference example: TR12345 maxLength: 100 */
    @get:JsonProperty("code")
    val code: kotlin.String? = null,

    /* Human-readable description of the transaction example: New Inflow Transaction maxLength: 256 */
    @get:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Additional custom attributes example: {\"reference\": \"TRANSACTION-001\", \"source\": \"api\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @get:JsonProperty("send")
    val send: CreateTransactionInflowSwaggerModelSend? = null

) {


}

