/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models

import com.midaz.client.transactions.models.CreateTransactionInflowSwaggerModelSendDistributeAmount

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param accountAlias Account identifier or alias example: {{accountAlias}} required: true
 * @param amount 
 * @param chartOfAccounts Chart of accounts code example: WITHDRAWAL_DEBIT
 * @param description Operation description example: Debit Operation
 * @param metadata Additional metadata example: {\"operation\": \"withdrawal\", \"type\": \"account\"}
 */


data class CreateTransactionOutflowSwaggerModelSendSourceFrom (

    /* Account identifier or alias example: {{accountAlias}} required: true */
    @get:JsonProperty("accountAlias")
    val accountAlias: kotlin.String? = null,

    @get:JsonProperty("amount")
    val amount: CreateTransactionInflowSwaggerModelSendDistributeAmount? = null,

    /* Chart of accounts code example: WITHDRAWAL_DEBIT */
    @get:JsonProperty("chartOfAccounts")
    val chartOfAccounts: kotlin.String? = null,

    /* Operation description example: Debit Operation */
    @get:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Additional metadata example: {\"operation\": \"withdrawal\", \"type\": \"account\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

