/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models

import com.midaz.client.transactions.models.CreateTransactionOutflowSwaggerModelSendSourceFrom

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Source accounts and amounts for the transaction required: true
 *
 * @param from List of source operations required: true
 */


data class CreateTransactionOutflowSwaggerModelSendSource (

    /* List of source operations required: true */
    @get:JsonProperty("from")
    val from: kotlin.collections.List<CreateTransactionOutflowSwaggerModelSendSourceFrom>? = null

) {


}

