/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * CreateAssetRateInput is the input payload to create an asset rate. Contains required fields for setting up asset conversion rates, including source and target assets, rate value, scale, and optional metadata.
 *
 * @param from Source asset code (required) example: USD required: true minLength: 2 maxLength: 10
 * @param rate Conversion rate value (required) example: 100 required: true
 * @param to Target asset code (required) example: BRL required: true minLength: 2 maxLength: 10
 * @param externalId External identifier for integration (optional) example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param metadata Additional custom attributes (optional) example: {\"provider\": \"Central Bank\", \"rateName\": \"Official Exchange Rate\"}
 * @param scale Decimal places for the rate (optional) example: 2 minimum: 0
 * @param source Source of rate information (optional) example: External System maxLength: 200
 * @param ttl Time-to-live in seconds (optional) example: 3600 minimum: 0
 */


data class CreateAssetRateInput (

    /* Source asset code (required) example: USD required: true minLength: 2 maxLength: 10 */
    @get:JsonProperty("from")
    val from: kotlin.String,

    /* Conversion rate value (required) example: 100 required: true */
    @get:JsonProperty("rate")
    val rate: kotlin.Int,

    /* Target asset code (required) example: BRL required: true minLength: 2 maxLength: 10 */
    @get:JsonProperty("to")
    val to: kotlin.String,

    /* External identifier for integration (optional) example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("externalId")
    val externalId: java.util.UUID? = null,

    /* Additional custom attributes (optional) example: {\"provider\": \"Central Bank\", \"rateName\": \"Official Exchange Rate\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Decimal places for the rate (optional) example: 2 minimum: 0 */
    @get:JsonProperty("scale")
    val scale: kotlin.Int? = null,

    /* Source of rate information (optional) example: External System maxLength: 200 */
    @get:JsonProperty("source")
    val source: kotlin.String? = null,

    /* Time-to-live in seconds (optional) example: 3600 minimum: 0 */
    @get:JsonProperty("ttl")
    val ttl: kotlin.Int? = null

) {


}

