/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models

import com.midaz.client.transactions.models.CreateTransactionInflowSwaggerModelSendDistributeTo

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Destination accounts and amounts for the transaction required: true
 *
 * @param to List of destination operations required: true
 */


data class CreateTransactionInflowSwaggerModelSendDistribute (

    /* List of destination operations required: true */
    @get:JsonProperty("to")
    val to: kotlin.collections.List<CreateTransactionInflowSwaggerModelSendDistributeTo>? = null

) {


}

