/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Amount details for the operation required: true
 *
 * @param asset Asset code example: USD required: true
 * @param `value` Amount value in smallest unit example: \"100.00\" required: true
 */


data class CreateTransactionInflowSwaggerModelSendDistributeAmount (

    /* Asset code example: USD required: true */
    @get:JsonProperty("asset")
    val asset: kotlin.String? = null,

    /* Amount value in smallest unit example: \"100.00\" required: true */
    @get:JsonProperty("value")
    val `value`: kotlin.String? = null

) {


}

