/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * CreateTransactionRouteInput payload
 *
 * @param operationRoutes An object containing accounting data of Operation Routes from the Transaction Route.
 * @param title Short text summarizing the purpose of the transaction. Used as an entry note for identification.
 * @param description A description for the Transaction Route.
 * @param metadata Additional metadata stored as JSON
 */


data class CreateTransactionRouteInput (

    /* An object containing accounting data of Operation Routes from the Transaction Route. */
    @get:JsonProperty("operationRoutes")
    val operationRoutes: kotlin.collections.List<kotlin.String>,

    /* Short text summarizing the purpose of the transaction. Used as an entry note for identification. */
    @get:JsonProperty("title")
    val title: kotlin.String,

    /* A description for the Transaction Route. */
    @get:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Additional metadata stored as JSON */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

