/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Standardized error response format used across all API endpoints for error situations. Provides structured information about errors including codes, messages, and field-specific validation details.
 *
 * @param code Error code identifying the specific error condition example: ERR_INVALID_INPUT maxLength: 50
 * @param entityType Optional type of entity associated with the error example: Organization maxLength: 100
 * @param fields Optional detailed field validations for client-side handling example: {\"name\": \"Field 'name' is required\"}
 * @param message Detailed error message explaining the issue example: The request contains invalid fields. Please check the field 'name' and try again. maxLength: 500
 * @param title Short, human-readable error title example: Bad Request maxLength: 100
 */


data class Error (

    /* Error code identifying the specific error condition example: ERR_INVALID_INPUT maxLength: 50 */
    @get:JsonProperty("code")
    val code: kotlin.String? = null,

    /* Optional type of entity associated with the error example: Organization maxLength: 100 */
    @get:JsonProperty("entityType")
    val entityType: kotlin.String? = null,

    /* Optional detailed field validations for client-side handling example: {\"name\": \"Field 'name' is required\"} */
    @get:JsonProperty("fields")
    val fields: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Detailed error message explaining the issue example: The request contains invalid fields. Please check the field 'name' and try again. maxLength: 500 */
    @get:JsonProperty("message")
    val message: kotlin.String? = null,

    /* Short, human-readable error title example: Bad Request maxLength: 100 */
    @get:JsonProperty("title")
    val title: kotlin.String? = null

) {


}

