/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models

import com.midaz.client.transactions.models.CreateTransactionInflowSwaggerModelSendDistribute
import com.midaz.client.transactions.models.GithubComLerianStudioMidazV3ComponentsTransactionInternalAdaptersPostgresTransactionCreateTransactionSwaggerModelSendSource

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Send operation details including source and distribution required: true
 *
 * @param asset Asset code for the transaction example: USD required: true
 * @param distribute 
 * @param source 
 * @param `value` Transaction amount value in the smallest unit of the asset example: \"100.00\" required: true
 */


data class GithubComLerianStudioMidazV3ComponentsTransactionInternalAdaptersPostgresTransactionCreateTransactionSwaggerModelSend (

    /* Asset code for the transaction example: USD required: true */
    @get:JsonProperty("asset")
    val asset: kotlin.String? = null,

    @get:JsonProperty("distribute")
    val distribute: CreateTransactionInflowSwaggerModelSendDistribute? = null,

    @get:JsonProperty("source")
    val source: GithubComLerianStudioMidazV3ComponentsTransactionInternalAdaptersPostgresTransactionCreateTransactionSwaggerModelSendSource? = null,

    /* Transaction amount value in the smallest unit of the asset example: \"100.00\" required: true */
    @get:JsonProperty("value")
    val `value`: kotlin.String? = null

) {


}

