/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models

import com.midaz.client.transactions.models.Pagination
import com.midaz.client.transactions.models.Transaction

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param pagination 
 * @param items 
 * @param limit 
 * @param nextCursor 
 * @param page 
 * @param prevCursor 
 */


data class InlineResponse2005 (

    @get:JsonProperty("Pagination")
    val pagination: Pagination? = null,

    @get:JsonProperty("items")
    val items: kotlin.collections.List<Transaction>? = null,

    @get:JsonProperty("limit")
    val limit: kotlin.Int? = null,

    @get:JsonProperty("next_cursor")
    val nextCursor: kotlin.String? = null,

    @get:JsonProperty("page")
    val page: kotlin.Any? = null,

    @get:JsonProperty("prev_cursor")
    val prevCursor: kotlin.String? = null

) {


}

