/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models

import com.midaz.client.transactions.models.MmodelBalance
import com.midaz.client.transactions.models.Pagination

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param nextCursor 
 * @param prevCursor 
 * @param pagination 
 * @param items 
 * @param limit 
 */


data class InlineResponse200 (

    @get:JsonProperty(" next_cursor")
    val nextCursor: kotlin.String? = null,

    @get:JsonProperty(" prev_cursor")
    val prevCursor: kotlin.String? = null,

    @get:JsonProperty("Pagination")
    val pagination: Pagination? = null,

    @get:JsonProperty("items")
    val items: kotlin.collections.List<MmodelBalance>? = null,

    @get:JsonProperty("limit")
    val limit: kotlin.Int? = null

) {


}

