/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models

import com.midaz.client.transactions.models.Amount
import com.midaz.client.transactions.models.Balance
import com.midaz.client.transactions.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Operation is a struct designed to store operation data. Represents a financial operation that affects account balances, including details such as amount, balance before and after, transaction association, and metadata.
 *
 * @param accountAlias Human-readable alias for the account example: @person1 maxLength: 256
 * @param accountId Account identifier associated with this operation example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param amount Operation amount information
 * @param assetCode Asset code for the operation example: BRL minLength: 2 maxLength: 10
 * @param balance Balance before the operation
 * @param balanceAfter Balance after the operation
 * @param balanceId Balance identifier affected by this operation example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param chartOfAccounts Chart of accounts code for accounting purposes example: 1000 maxLength: 20
 * @param createdAt Timestamp when the operation was created example: 2021-01-01T00:00:00Z format: date-time
 * @param deletedAt Timestamp when the operation was deleted (if soft-deleted) example: 2021-01-01T00:00:00Z format: date-time
 * @param description Human-readable description of the operation example: Credit card operation maxLength: 256
 * @param id Unique identifier for the operation example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param ledgerId Ledger identifier example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param metadata Additional custom attributes example: {\"reason\": \"Purchase refund\", \"reference\": \"INV-12345\"}
 * @param organizationId Organization identifier example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param route Route example: 00000000-0000-0000-0000-000000000000 format: string
 * @param status Operation status information
 * @param transactionId Parent transaction identifier example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param type Type of operation (e.g., DEBIT, CREDIT) example: DEBIT maxLength: 50
 * @param updatedAt Timestamp when the operation was last updated example: 2021-01-01T00:00:00Z format: date-time
 */


data class Operation (

    /* Human-readable alias for the account example: @person1 maxLength: 256 */
    @get:JsonProperty("accountAlias")
    val accountAlias: kotlin.String? = null,

    /* Account identifier associated with this operation example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("accountId")
    val accountId: java.util.UUID? = null,

    /* Operation amount information */
    @get:JsonProperty("amount")
    val amount: Amount? = null,

    /* Asset code for the operation example: BRL minLength: 2 maxLength: 10 */
    @get:JsonProperty("assetCode")
    val assetCode: kotlin.String? = null,

    /* Balance before the operation */
    @get:JsonProperty("balance")
    val balance: Balance? = null,

    /* Balance after the operation */
    @get:JsonProperty("balanceAfter")
    val balanceAfter: Balance? = null,

    /* Balance identifier affected by this operation example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("balanceId")
    val balanceId: java.util.UUID? = null,

    /* Chart of accounts code for accounting purposes example: 1000 maxLength: 20 */
    @get:JsonProperty("chartOfAccounts")
    val chartOfAccounts: kotlin.String? = null,

    /* Timestamp when the operation was created example: 2021-01-01T00:00:00Z format: date-time */
    @get:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    /* Timestamp when the operation was deleted (if soft-deleted) example: 2021-01-01T00:00:00Z format: date-time */
    @get:JsonProperty("deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    /* Human-readable description of the operation example: Credit card operation maxLength: 256 */
    @get:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Unique identifier for the operation example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("id")
    val id: java.util.UUID? = null,

    /* Ledger identifier example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("ledgerId")
    val ledgerId: java.util.UUID? = null,

    /* Additional custom attributes example: {\"reason\": \"Purchase refund\", \"reference\": \"INV-12345\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Organization identifier example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("organizationId")
    val organizationId: java.util.UUID? = null,

    /* Route example: 00000000-0000-0000-0000-000000000000 format: string */
    @get:JsonProperty("route")
    val route: kotlin.String? = null,

    /* Operation status information */
    @get:JsonProperty("status")
    val status: Status? = null,

    /* Parent transaction identifier example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("transactionId")
    val transactionId: java.util.UUID? = null,

    /* Type of operation (e.g., DEBIT, CREDIT) example: DEBIT maxLength: 50 */
    @get:JsonProperty("type")
    val type: kotlin.String? = null,

    /* Timestamp when the operation was last updated example: 2021-01-01T00:00:00Z format: date-time */
    @get:JsonProperty("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

