/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Pagination is the struct designed to store the pagination data of an entity list.
 *
 * @param items 
 * @param limit 
 * @param nextCursor 
 * @param page 
 * @param prevCursor 
 */


data class Pagination (

    @get:JsonProperty("items")
    val items: kotlin.Any? = null,

    @get:JsonProperty("limit")
    val limit: kotlin.Int? = null,

    @get:JsonProperty("next_cursor")
    val nextCursor: kotlin.String? = null,

    @get:JsonProperty("page")
    val page: kotlin.Int? = null,

    @get:JsonProperty("prev_cursor")
    val prevCursor: kotlin.String? = null

) {


}

