/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Status is the struct designed to represent the status of a transaction. Contains code and optional description for transaction states.
 *
 * @param code Status code identifying the state of the transaction example: ACTIVE maxLength: 100
 * @param description Optional descriptive text explaining the status example: Active status maxLength: 256
 */


data class Status (

    /* Status code identifying the state of the transaction example: ACTIVE maxLength: 100 */
    @get:JsonProperty("code")
    val code: kotlin.String? = null,

    /* Optional descriptive text explaining the status example: Active status maxLength: 256 */
    @get:JsonProperty("description")
    val description: kotlin.String? = null

) {


}

