/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models

import com.midaz.client.transactions.models.OperationRoute

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * TransactionRoute object
 *
 * @param createdAt The timestamp when the transaction route was created.
 * @param deletedAt The timestamp when the transaction route was deleted.
 * @param description A description for the Transaction Route.
 * @param id The unique identifier of the Transaction Route.
 * @param ledgerId The unique identifier of the Ledger.
 * @param metadata Additional metadata stored as JSON
 * @param operationRoutes An object containing accounting data of Operation Routes from the Transaction Route.
 * @param organizationId The unique identifier of the Organization.
 * @param title Short text summarizing the purpose of the transaction. Used as an entry note for identification.
 * @param updatedAt The timestamp when the transaction route was last updated.
 */


data class TransactionRoute (

    /* The timestamp when the transaction route was created. */
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String? = null,

    /* The timestamp when the transaction route was deleted. */
    @get:JsonProperty("deletedAt")
    val deletedAt: kotlin.String? = null,

    /* A description for the Transaction Route. */
    @get:JsonProperty("description")
    val description: kotlin.String? = null,

    /* The unique identifier of the Transaction Route. */
    @get:JsonProperty("id")
    val id: kotlin.String? = null,

    /* The unique identifier of the Ledger. */
    @get:JsonProperty("ledgerId")
    val ledgerId: kotlin.String? = null,

    /* Additional metadata stored as JSON */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* An object containing accounting data of Operation Routes from the Transaction Route. */
    @get:JsonProperty("operationRoutes")
    val operationRoutes: kotlin.collections.List<OperationRoute>? = null,

    /* The unique identifier of the Organization. */
    @get:JsonProperty("organizationId")
    val organizationId: kotlin.String? = null,

    /* Short text summarizing the purpose of the transaction. Used as an entry note for identification. */
    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    /* The timestamp when the transaction route was last updated. */
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String? = null

) {


}

