/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Request payload for updating an existing balance's permissions. All fields are optional - only specified fields will be updated. Omitted fields will remain unchanged.
 *
 * @param allowReceiving Whether the account should be allowed to receive funds to this balance required: false example: true
 * @param allowSending Whether the account should be allowed to send funds from this balance required: false example: true
 */


data class UpdateBalance (

    /* Whether the account should be allowed to receive funds to this balance required: false example: true */
    @get:JsonProperty("allowReceiving")
    val allowReceiving: kotlin.Boolean? = null,

    /* Whether the account should be allowed to send funds from this balance required: false example: true */
    @get:JsonProperty("allowSending")
    val allowSending: kotlin.Boolean? = null

) {


}

