/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * UpdateOperationInput is the input payload to update an operation. Contains fields that can be modified after an operation is created.
 *
 * @param description Human-readable description of the operation example: Credit card operation maxLength: 256
 * @param metadata Additional custom attributes example: {\"reason\": \"Purchase refund\", \"reference\": \"INV-12345\"}
 */


data class UpdateOperationInput (

    /* Human-readable description of the operation example: Credit card operation maxLength: 256 */
    @get:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Additional custom attributes example: {\"reason\": \"Purchase refund\", \"reference\": \"INV-12345\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

