/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * UpdateOperationRouteInput payload
 *
 * @param account The account selection rule configuration.
 * @param description Detailed description of the operation route purpose and usage.
 * @param metadata Additional metadata stored as JSON
 * @param title Short text summarizing the purpose of the operation. Used as an entry note for identification.
 */


data class UpdateOperationRouteInput (

    /* The account selection rule configuration. */
    @get:JsonProperty("account")
    val account: kotlin.Any? = null,

    /* Detailed description of the operation route purpose and usage. */
    @get:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Additional metadata stored as JSON */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Short text summarizing the purpose of the operation. Used as an entry note for identification. */
    @get:JsonProperty("title")
    val title: kotlin.String? = null

) {


}

