/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * UpdateTransactionInput is the input payload to update a transaction. Contains fields that can be modified after a transaction is created.
 *
 * @param description Human-readable description of the transaction example: Transaction description maxLength: 256
 * @param metadata Additional custom attributes example: {\"purpose\": \"Monthly payment\", \"category\": \"Utility\"}
 */


data class UpdateTransactionInput (

    /* Human-readable description of the transaction example: Transaction description maxLength: 256 */
    @get:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Additional custom attributes example: {\"purpose\": \"Monthly payment\", \"category\": \"Utility\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

