/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * AccountType object
 *
 * @param createdAt The timestamp when the account type was created.
 * @param deletedAt The timestamp when the account type was deleted.
 * @param description Detailed description of the account type.
 * @param id The unique identifier of the Account Type.
 * @param keyValue A unique key value identifier for the account type.
 * @param ledgerId The unique identifier of the Ledger.
 * @param metadata Custom key-value pairs for extending the account type information example: {\"department\": \"Treasury\", \"purpose\": \"Operating Expenses\", \"region\": \"Global\"}
 * @param name The name of the account type.
 * @param organizationId The unique identifier of the Organization.
 * @param updatedAt The timestamp when the account type was last updated.
 */


data class AccountType (

    /* The timestamp when the account type was created. */
    @get:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    /* The timestamp when the account type was deleted. */
    @get:JsonProperty("deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    /* Detailed description of the account type. */
    @get:JsonProperty("description")
    val description: kotlin.String? = null,

    /* The unique identifier of the Account Type. */
    @get:JsonProperty("id")
    val id: kotlin.String? = null,

    /* A unique key value identifier for the account type. */
    @get:JsonProperty("keyValue")
    val keyValue: kotlin.String? = null,

    /* The unique identifier of the Ledger. */
    @get:JsonProperty("ledgerId")
    val ledgerId: kotlin.String? = null,

    /* Custom key-value pairs for extending the account type information example: {\"department\": \"Treasury\", \"purpose\": \"Operating Expenses\", \"region\": \"Global\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* The name of the account type. */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* The unique identifier of the Organization. */
    @get:JsonProperty("organizationId")
    val organizationId: kotlin.String? = null,

    /* The timestamp when the account type was last updated. */
    @get:JsonProperty("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

