/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Structured address information following standard postal address format. Country field follows ISO 3166-1 alpha-2 standard (2-letter country codes). Used for organization physical locations and other address needs.
 *
 * @param city City or locality name example: New York maxLength: 100
 * @param country Country code in ISO 3166-1 alpha-2 format (two-letter country code) example: US minLength: 2 maxLength: 2
 * @param line1 Primary address line (street address or PO Box) example: 123 Financial Avenue maxLength: 256
 * @param line2 Secondary address information like apartment number, suite, or floor example: Suite 1500 maxLength: 256
 * @param state State, province, or region name or code example: NY maxLength: 100
 * @param zipCode Postal code or ZIP code example: 10001 maxLength: 20
 */


data class Address (

    /* City or locality name example: New York maxLength: 100 */
    @get:JsonProperty("city")
    val city: kotlin.String? = null,

    /* Country code in ISO 3166-1 alpha-2 format (two-letter country code) example: US minLength: 2 maxLength: 2 */
    @get:JsonProperty("country")
    val country: kotlin.String? = null,

    /* Primary address line (street address or PO Box) example: 123 Financial Avenue maxLength: 256 */
    @get:JsonProperty("line1")
    val line1: kotlin.String? = null,

    /* Secondary address information like apartment number, suite, or floor example: Suite 1500 maxLength: 256 */
    @get:JsonProperty("line2")
    val line2: kotlin.String? = null,

    /* State, province, or region name or code example: NY maxLength: 100 */
    @get:JsonProperty("state")
    val state: kotlin.String? = null,

    /* Postal code or ZIP code example: 10001 maxLength: 20 */
    @get:JsonProperty("zipCode")
    val zipCode: kotlin.String? = null

) {


}

