/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Asset represents a financial instrument within a ledger, such as a currency, cryptocurrency, commodity, or other asset type.
 *
 * @param code Unique code/symbol for the asset (max length 100 characters)
 * @param createdAt Timestamp when the asset was created
 * @param deletedAt Timestamp when the asset was deleted (null if not deleted)
 * @param id Unique identifier for the asset (UUID format)
 * @param ledgerId ID of the ledger this asset belongs to (UUID format)
 * @param metadata Additional custom attributes for the asset
 * @param name Name of the asset (max length 256 characters)
 * @param organizationId ID of the organization that owns this asset (UUID format)
 * @param status Status of the asset (active, inactive, pending)
 * @param type Type of the asset (e.g., currency, cryptocurrency, commodity, stock)
 * @param updatedAt Timestamp when the asset was last updated
 */


data class Asset (

    /* Unique code/symbol for the asset (max length 100 characters) */
    @get:JsonProperty("code")
    val code: kotlin.String? = null,

    /* Timestamp when the asset was created */
    @get:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    /* Timestamp when the asset was deleted (null if not deleted) */
    @get:JsonProperty("deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    /* Unique identifier for the asset (UUID format) */
    @get:JsonProperty("id")
    val id: java.util.UUID? = null,

    /* ID of the ledger this asset belongs to (UUID format) */
    @get:JsonProperty("ledgerId")
    val ledgerId: java.util.UUID? = null,

    /* Additional custom attributes for the asset */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Name of the asset (max length 256 characters) */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* ID of the organization that owns this asset (UUID format) */
    @get:JsonProperty("organizationId")
    val organizationId: java.util.UUID? = null,

    /* Status of the asset (active, inactive, pending) */
    @get:JsonProperty("status")
    val status: Status? = null,

    /* Type of the asset (e.g., currency, cryptocurrency, commodity, stock) */
    @get:JsonProperty("type")
    val type: kotlin.String? = null,

    /* Timestamp when the asset was last updated */
    @get:JsonProperty("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

