/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * CreateSegmentInput is the input payload to create a segment within a ledger, representing a logical division such as a business area, product line, or customer category.
 *
 * @param name Name of the segment (required, max length 256 characters)
 * @param metadata Additional custom attributes for the segment Keys max length: 100 characters, Values max length: 2000 characters
 * @param status Status of the segment (active, inactive, pending)
 */


data class CreateSegmentInput (

    /* Name of the segment (required, max length 256 characters) */
    @get:JsonProperty("name")
    val name: kotlin.String,

    /* Additional custom attributes for the segment Keys max length: 100 characters, Values max length: 2000 characters */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Status of the segment (active, inactive, pending) */
    @get:JsonProperty("status")
    val status: Status? = null

) {


}

