/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * CreatePortfolioInput is the input payload to create a portfolio within a ledger, representing a collection of accounts grouped for specific purposes.
 *
 * @param name Name of the portfolio (required, max length 256 characters)
 * @param entityId Optional external entity identifier (max length 256 characters)
 * @param metadata Additional custom attributes for the portfolio Keys max length: 100 characters, Values max length: 2000 characters
 * @param status Status of the portfolio (active, inactive, pending)
 */


data class CreatePortfolioInput (

    /* Name of the portfolio (required, max length 256 characters) */
    @get:JsonProperty("name")
    val name: kotlin.String,

    /* Optional external entity identifier (max length 256 characters) */
    @get:JsonProperty("entityId")
    val entityId: kotlin.String? = null,

    /* Additional custom attributes for the portfolio Keys max length: 100 characters, Values max length: 2000 characters */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Status of the portfolio (active, inactive, pending) */
    @get:JsonProperty("status")
    val status: Status? = null

) {


}

