/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * CreateAssetInput is the input payload to create an asset within a ledger, such as a currency, cryptocurrency, or other financial instrument.
 *
 * @param code Unique code/symbol for the asset (required, max length 100 characters)
 * @param name Name of the asset (required, max length 256 characters)
 * @param type Type of the asset (e.g., currency, cryptocurrency, commodity, stock)
 * @param metadata Additional custom attributes for the asset Keys max length: 100 characters, Values max length: 2000 characters
 * @param status Status of the asset (active, inactive, pending)
 */


data class CreateAssetInput (

    /* Unique code/symbol for the asset (required, max length 100 characters) */
    @get:JsonProperty("code")
    val code: kotlin.String,

    /* Name of the asset (required, max length 256 characters) */
    @get:JsonProperty("name")
    val name: kotlin.String,

    /* Type of the asset (e.g., currency, cryptocurrency, commodity, stock) */
    @get:JsonProperty("type")
    val type: kotlin.String,

    /* Additional custom attributes for the asset Keys max length: 100 characters, Values max length: 2000 characters */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Status of the asset (active, inactive, pending) */
    @get:JsonProperty("status")
    val status: Status? = null

) {


}

