/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Request payload for creating a new ledger. Contains the ledger name (required), status, and optional metadata. Ledgers are organizational units within an organization that group related financial accounts and assets together.
 *
 * @param name Display name of the ledger required: true maxLength: 256
 * @param metadata Custom key-value pairs for extending the ledger information required: false example: {\"department\": \"Finance\", \"currency\": \"USD\", \"region\": \"North America\"}
 * @param status Current operating status of the ledger (defaults to ACTIVE if not specified) required: false
 */


data class CreateLedgerInput (

    /* Display name of the ledger required: true maxLength: 256 */
    @get:JsonProperty("name")
    val name: kotlin.String,

    /* Custom key-value pairs for extending the ledger information required: false example: {\"department\": \"Finance\", \"currency\": \"USD\", \"region\": \"North America\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Current operating status of the ledger (defaults to ACTIVE if not specified) required: false */
    @get:JsonProperty("status")
    val status: Status? = null

) {


}

