/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Organization
import com.midaz.client.onboarding.models.Pagination

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param pagination 
 * @param items 
 * @param limit 
 * @param page 
 */


data class InlineResponse200 (

    @get:JsonProperty("Pagination")
    val pagination: Pagination? = null,

    @get:JsonProperty("items")
    val items: kotlin.collections.List<Organization>? = null,

    @get:JsonProperty("limit")
    val limit: kotlin.Int? = null,

    @get:JsonProperty("page")
    val page: kotlin.Int? = null

) {


}

