/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Address
import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Complete organization entity containing all fields including system-generated fields like ID, creation timestamps, and metadata. This is the response format for organization operations. Organizations are the top-level entities in the Midaz platform hierarchy.
 *
 * @param address Physical address of the organization
 * @param createdAt Timestamp when the organization was created (RFC3339 format) example: 2021-01-01T00:00:00Z format: date-time
 * @param deletedAt Timestamp when the organization was soft deleted, null if not deleted (RFC3339 format) example: null format: date-time
 * @param doingBusinessAs Trading or brand name of the organization, if different from legal name example: Lerian FS maxLength: 256
 * @param id Unique identifier for the organization (UUID format) example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param legalDocument Official tax ID, company registration number, or other legal identification example: 123456789012345 maxLength: 256
 * @param legalName Official legal name of the organization example: Lerian Financial Services Ltd. maxLength: 256
 * @param metadata Custom key-value pairs for extending the organization information example: {\"industry\": \"Financial Services\", \"founded\": 2020, \"employees\": 150}
 * @param parentOrganizationId Reference to the parent organization, if this is a child organization example: 00000000-0000-0000-0000-000000000000 format: uuid
 * @param status Current operating status of the organization
 * @param updatedAt Timestamp when the organization was last updated (RFC3339 format) example: 2021-01-01T00:00:00Z format: date-time
 */


data class Organization (

    /* Physical address of the organization */
    @get:JsonProperty("address")
    val address: Address? = null,

    /* Timestamp when the organization was created (RFC3339 format) example: 2021-01-01T00:00:00Z format: date-time */
    @get:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    /* Timestamp when the organization was soft deleted, null if not deleted (RFC3339 format) example: null format: date-time */
    @get:JsonProperty("deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    /* Trading or brand name of the organization, if different from legal name example: Lerian FS maxLength: 256 */
    @get:JsonProperty("doingBusinessAs")
    val doingBusinessAs: kotlin.String? = null,

    /* Unique identifier for the organization (UUID format) example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("id")
    val id: java.util.UUID? = null,

    /* Official tax ID, company registration number, or other legal identification example: 123456789012345 maxLength: 256 */
    @get:JsonProperty("legalDocument")
    val legalDocument: kotlin.String? = null,

    /* Official legal name of the organization example: Lerian Financial Services Ltd. maxLength: 256 */
    @get:JsonProperty("legalName")
    val legalName: kotlin.String? = null,

    /* Custom key-value pairs for extending the organization information example: {\"industry\": \"Financial Services\", \"founded\": 2020, \"employees\": 150} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Reference to the parent organization, if this is a child organization example: 00000000-0000-0000-0000-000000000000 format: uuid */
    @get:JsonProperty("parentOrganizationId")
    val parentOrganizationId: java.util.UUID? = null,

    /* Current operating status of the organization */
    @get:JsonProperty("status")
    val status: Status? = null,

    /* Timestamp when the organization was last updated (RFC3339 format) example: 2021-01-01T00:00:00Z format: date-time */
    @get:JsonProperty("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

