/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Portfolio represents a collection of accounts grouped for specific purposes such as business units, departments, or client portfolios.
 *
 * @param createdAt Timestamp when the portfolio was created
 * @param deletedAt Timestamp when the portfolio was deleted (null if not deleted)
 * @param entityId Optional external entity identifier (max length 256 characters)
 * @param id Unique identifier for the portfolio (UUID format)
 * @param ledgerId ID of the ledger this portfolio belongs to (UUID format)
 * @param metadata Additional custom attributes for the portfolio
 * @param name Name of the portfolio (max length 256 characters)
 * @param organizationId ID of the organization that owns this portfolio (UUID format)
 * @param status Status of the portfolio (active, inactive, pending)
 * @param updatedAt Timestamp when the portfolio was last updated
 */


data class Portfolio (

    /* Timestamp when the portfolio was created */
    @get:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    /* Timestamp when the portfolio was deleted (null if not deleted) */
    @get:JsonProperty("deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    /* Optional external entity identifier (max length 256 characters) */
    @get:JsonProperty("entityId")
    val entityId: kotlin.String? = null,

    /* Unique identifier for the portfolio (UUID format) */
    @get:JsonProperty("id")
    val id: java.util.UUID? = null,

    /* ID of the ledger this portfolio belongs to (UUID format) */
    @get:JsonProperty("ledgerId")
    val ledgerId: java.util.UUID? = null,

    /* Additional custom attributes for the portfolio */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Name of the portfolio (max length 256 characters) */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* ID of the organization that owns this portfolio (UUID format) */
    @get:JsonProperty("organizationId")
    val organizationId: java.util.UUID? = null,

    /* Status of the portfolio (active, inactive, pending) */
    @get:JsonProperty("status")
    val status: Status? = null,

    /* Timestamp when the portfolio was last updated */
    @get:JsonProperty("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

