/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Segment represents a logical division within a ledger such as a business area, product line, or customer category.
 *
 * @param createdAt Timestamp when the segment was created
 * @param deletedAt Timestamp when the segment was deleted (null if not deleted)
 * @param id Unique identifier for the segment (UUID format)
 * @param ledgerId ID of the ledger this segment belongs to (UUID format)
 * @param metadata Additional custom attributes for the segment
 * @param name Name of the segment (max length 256 characters)
 * @param organizationId ID of the organization that owns this segment (UUID format)
 * @param status Status of the segment (active, inactive, pending)
 * @param updatedAt Timestamp when the segment was last updated
 */


data class Segment (

    /* Timestamp when the segment was created */
    @get:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    /* Timestamp when the segment was deleted (null if not deleted) */
    @get:JsonProperty("deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    /* Unique identifier for the segment (UUID format) */
    @get:JsonProperty("id")
    val id: java.util.UUID? = null,

    /* ID of the ledger this segment belongs to (UUID format) */
    @get:JsonProperty("ledgerId")
    val ledgerId: java.util.UUID? = null,

    /* Additional custom attributes for the segment */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Name of the segment (max length 256 characters) */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* ID of the organization that owns this segment (UUID format) */
    @get:JsonProperty("organizationId")
    val organizationId: java.util.UUID? = null,

    /* Status of the segment (active, inactive, pending) */
    @get:JsonProperty("status")
    val status: Status? = null,

    /* Timestamp when the segment was last updated */
    @get:JsonProperty("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

