/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Entity status information with a standardized code and optional description. Common status codes include: ACTIVE, INACTIVE, PENDING, SUSPENDED, DELETED.
 *
 * @param code Status code identifier, common values include: ACTIVE, INACTIVE, PENDING, SUSPENDED, DELETED
 * @param description Optional human-readable description of the status
 */


data class Status (

    /* Status code identifier, common values include: ACTIVE, INACTIVE, PENDING, SUSPENDED, DELETED */
    @get:JsonProperty("code")
    val code: kotlin.String? = null,

    /* Optional human-readable description of the status */
    @get:JsonProperty("description")
    val description: kotlin.String? = null

) {


}

