/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Request payload for updating an existing account. All fields are optional - only specified fields will be updated. Omitted fields will remain unchanged. This allows partial updates to account properties such as name, status, portfolio, segment, and metadata.
 *
 * @param entityId Optional external identifier for linking to external systems required: false example: EXT-ACC-12345 maxLength: 256
 * @param metadata Updated custom key-value pairs for extending the account information required: false example: {\"department\": \"Global Treasury\", \"purpose\": \"Primary Operations\", \"region\": \"Global\"}
 * @param name Updated name of the account required: false example: Primary Corporate Checking Account maxLength: 256
 * @param portfolioId Updated portfolio ID for the account required: false format: uuid
 * @param segmentId Updated segment ID for the account required: false format: uuid
 * @param status Updated status of the account required: false
 */


data class UpdateAccountInput (

    /* Optional external identifier for linking to external systems required: false example: EXT-ACC-12345 maxLength: 256 */
    @get:JsonProperty("entityId")
    val entityId: kotlin.String? = null,

    /* Updated custom key-value pairs for extending the account information required: false example: {\"department\": \"Global Treasury\", \"purpose\": \"Primary Operations\", \"region\": \"Global\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Updated name of the account required: false example: Primary Corporate Checking Account maxLength: 256 */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Updated portfolio ID for the account required: false format: uuid */
    @get:JsonProperty("portfolioId")
    val portfolioId: java.util.UUID? = null,

    /* Updated segment ID for the account required: false format: uuid */
    @get:JsonProperty("segmentId")
    val segmentId: java.util.UUID? = null,

    /* Updated status of the account required: false */
    @get:JsonProperty("status")
    val status: Status? = null

) {


}

