/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Address
import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Request payload for updating an existing organization. All fields are optional - only specified fields will be updated. Omitted fields will remain unchanged.
 *
 * @param address Updated physical address of the organization required: false
 * @param doingBusinessAs Updated trading or brand name of the organization required: false example: Lerian Group maxLength: 256
 * @param legalName Updated legal name of the organization required: false example: Lerian Financial Group Ltd. maxLength: 256
 * @param metadata Updated custom key-value pairs for extending the organization information required: false example: {\"industry\": \"Financial Technology\", \"founded\": 2020, \"employees\": 200, \"headquarters\": \"New York\"}
 * @param parentOrganizationId Updated UUID of the parent organization if this is a child organization required: false format: uuid
 * @param status Updated status of the organization required: false
 */


data class UpdateOrganizationInput (

    /* Updated physical address of the organization required: false */
    @get:JsonProperty("address")
    val address: Address? = null,

    /* Updated trading or brand name of the organization required: false example: Lerian Group maxLength: 256 */
    @get:JsonProperty("doingBusinessAs")
    val doingBusinessAs: kotlin.String? = null,

    /* Updated legal name of the organization required: false example: Lerian Financial Group Ltd. maxLength: 256 */
    @get:JsonProperty("legalName")
    val legalName: kotlin.String? = null,

    /* Updated custom key-value pairs for extending the organization information required: false example: {\"industry\": \"Financial Technology\", \"founded\": 2020, \"employees\": 200, \"headquarters\": \"New York\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Updated UUID of the parent organization if this is a child organization required: false format: uuid */
    @get:JsonProperty("parentOrganizationId")
    val parentOrganizationId: java.util.UUID? = null,

    /* Updated status of the organization required: false */
    @get:JsonProperty("status")
    val status: Status? = null

) {


}

