/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Request payload for updating an existing ledger. All fields are optional - only specified fields will be updated. Omitted fields will remain unchanged.
 *
 * @param metadata Updated custom key-value pairs for extending the ledger information required: false example: {\"department\": \"Global Finance\", \"currency\": \"USD\", \"region\": \"Global\"}
 * @param name Updated display name of the ledger required: false example: Treasury Operations Global maxLength: 256
 * @param status Updated status of the ledger required: false
 */


data class UpdateLedgerInput (

    /* Updated custom key-value pairs for extending the ledger information required: false example: {\"department\": \"Global Finance\", \"currency\": \"USD\", \"region\": \"Global\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Updated display name of the ledger required: false example: Treasury Operations Global maxLength: 256 */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Updated status of the ledger required: false */
    @get:JsonProperty("status")
    val status: Status? = null

) {


}

