/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * UpdateAccountTypeInput payload
 *
 * @param description Detailed description of the account type.
 * @param metadata Custom key-value pairs for extending the account type information required: false example: {\"department\": \"Treasury\", \"purpose\": \"Operating Expenses\", \"region\": \"Global\"}
 * @param name The name of the account type.
 */


data class UpdateAccountTypeInput (

    /* Detailed description of the account type. */
    @get:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Custom key-value pairs for extending the account type information required: false example: {\"department\": \"Treasury\", \"purpose\": \"Operating Expenses\", \"region\": \"Global\"} */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* The name of the account type. */
    @get:JsonProperty("name")
    val name: kotlin.String? = null

) {


}

