/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.onboarding.models

import com.midaz.client.onboarding.models.Status

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * UpdateSegmentInput is the input payload to update an existing segment's properties such as name, status, and metadata.
 *
 * @param metadata Updated or additional custom attributes for the segment Keys max length: 100 characters, Values max length: 2000 characters
 * @param name Updated name of the segment (optional, max length 256 characters)
 * @param status Updated status of the segment (active, inactive, pending)
 */


data class UpdateSegmentInput (

    /* Updated or additional custom attributes for the segment Keys max length: 100 characters, Values max length: 2000 characters */
    @get:JsonProperty("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Updated name of the segment (optional, max length 256 characters) */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Updated status of the segment (active, inactive, pending) */
    @get:JsonProperty("status")
    val status: Status? = null

) {


}

