/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.apis

import com.fasterxml.jackson.annotation.JsonProperty

import org.springframework.web.client.RestClient
import org.springframework.web.client.RestClientResponseException

import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
import org.springframework.http.ResponseEntity
import org.springframework.http.MediaType


import com.midaz.client.transactions.models.Error
import com.midaz.client.transactions.models.InlineResponse200
import com.midaz.client.transactions.models.MmodelBalance
import com.midaz.client.transactions.models.UpdateBalance
import com.midaz.client.transactions.infrastructure.*

class BalancesApi(client: RestClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(RestClient.builder()
        .baseUrl(baseUrl)
        .messageConverters { it.add(MappingJackson2HttpMessageConverter()) }
        .build()
    )


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdBalancesGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, accountId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: kotlin.String? = null, cursor: kotlin.String? = null): InlineResponse200 {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdBalancesGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, accountId = accountId, xRequestId = xRequestId, limit = limit, startDate = startDate, endDate = endDate, sortOrder = sortOrder, cursor = cursor)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdBalancesGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, accountId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: kotlin.String? = null, cursor: kotlin.String? = null): ResponseEntity<InlineResponse200> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdBalancesGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, accountId = accountId, xRequestId = xRequestId, limit = limit, startDate = startDate, endDate = endDate, sortOrder = sortOrder, cursor = cursor)
        return request<Unit, InlineResponse200>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdBalancesGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, accountId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: kotlin.String? = null, cursor: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (startDate != null) {
                    put("start_date", listOf(startDate.toString()))
                }
                if (endDate != null) {
                    put("end_date", listOf(endDate.toString()))
                }
                if (sortOrder != null) {
                    put("sort_order", listOf(sortOrder.toString()))
                }
                if (cursor != null) {
                    put("cursor", listOf(cursor.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "account_id" to accountId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/accounts/{account_id}/balances",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAliasAliasBalancesGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, alias: kotlin.String, xRequestId: kotlin.String? = null): InlineResponse200 {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAliasAliasBalancesGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, alias = alias, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAliasAliasBalancesGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, alias: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<InlineResponse200> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAliasAliasBalancesGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, alias = alias, xRequestId = xRequestId)
        return request<Unit, InlineResponse200>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAliasAliasBalancesGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, alias: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "alias" to alias,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/accounts/alias/{alias}/balances",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsExternalCodeBalancesGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, code: kotlin.String, xRequestId: kotlin.String? = null): InlineResponse200 {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdAccountsExternalCodeBalancesGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, code = code, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsExternalCodeBalancesGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, code: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<InlineResponse200> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdAccountsExternalCodeBalancesGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, code = code, xRequestId = xRequestId)
        return request<Unit, InlineResponse200>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsExternalCodeBalancesGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, code: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "code" to code,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/accounts/external/{code}/balances",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdDelete(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, balanceId: kotlin.String, xRequestId: kotlin.String? = null): kotlin.String {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdDeleteWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, balanceId = balanceId, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdDeleteWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, balanceId: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<kotlin.String> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdDeleteRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, balanceId = balanceId, xRequestId = xRequestId)
        return request<Unit, kotlin.String>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdDeleteRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, balanceId: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "balance_id" to balanceId,
        )

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/balances/{balance_id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, balanceId: kotlin.String, xRequestId: kotlin.String? = null): MmodelBalance {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, balanceId = balanceId, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, balanceId: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<MmodelBalance> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, balanceId = balanceId, xRequestId = xRequestId)
        return request<Unit, MmodelBalance>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, balanceId: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "balance_id" to balanceId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/balances/{balance_id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdPatch(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, balanceId: kotlin.String, balance: UpdateBalance, xRequestId: kotlin.String? = null): MmodelBalance {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdPatchWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, balanceId = balanceId, balance = balance, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdPatchWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, balanceId: kotlin.String, balance: UpdateBalance, xRequestId: kotlin.String? = null): ResponseEntity<MmodelBalance> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdPatchRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, balanceId = balanceId, balance = balance, xRequestId = xRequestId)
        return request<UpdateBalance, MmodelBalance>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesBalanceIdPatchRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, balanceId: kotlin.String, balance: UpdateBalance, xRequestId: kotlin.String? = null) : RequestConfig<UpdateBalance> {
        val localVariableBody = balance
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "balance_id" to balanceId,
        )

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/balances/{balance_id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: kotlin.String? = null, cursor: kotlin.String? = null): InlineResponse200 {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdBalancesGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, xRequestId = xRequestId, limit = limit, startDate = startDate, endDate = endDate, sortOrder = sortOrder, cursor = cursor)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: kotlin.String? = null, cursor: kotlin.String? = null): ResponseEntity<InlineResponse200> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdBalancesGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, xRequestId = xRequestId, limit = limit, startDate = startDate, endDate = endDate, sortOrder = sortOrder, cursor = cursor)
        return request<Unit, InlineResponse200>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdBalancesGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: kotlin.String? = null, cursor: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (startDate != null) {
                    put("start_date", listOf(startDate.toString()))
                }
                if (endDate != null) {
                    put("end_date", listOf(endDate.toString()))
                }
                if (sortOrder != null) {
                    put("sort_order", listOf(sortOrder.toString()))
                }
                if (cursor != null) {
                    put("cursor", listOf(cursor.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/balances",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

}
