/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.apis

import com.fasterxml.jackson.annotation.JsonProperty

import org.springframework.web.client.RestClient
import org.springframework.web.client.RestClientResponseException

import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
import org.springframework.http.ResponseEntity
import org.springframework.http.MediaType


import com.midaz.client.transactions.models.Error
import com.midaz.client.transactions.models.InlineResponse2003
import com.midaz.client.transactions.models.OperationRoute
import com.midaz.client.transactions.models.UpdateOperationRouteInput
import com.midaz.client.transactions.infrastructure.*

class OperationRouteApi(client: RestClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(RestClient.builder()
        .baseUrl(baseUrl)
        .messageConverters { it.add(MappingJackson2HttpMessageConverter()) }
        .build()
    )

    /**
     * enum for parameter sortOrder
     */
    enum class SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesGet(val value: kotlin.String) {
        @JsonProperty(value = "asc") asc("asc"),
        @JsonProperty(value = "desc") desc("desc")
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesGet? = null, cursor: kotlin.String? = null): InlineResponse2003 {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, xRequestId = xRequestId, limit = limit, startDate = startDate, endDate = endDate, sortOrder = sortOrder, cursor = cursor)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesGet? = null, cursor: kotlin.String? = null): ResponseEntity<InlineResponse2003> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, xRequestId = xRequestId, limit = limit, startDate = startDate, endDate = endDate, sortOrder = sortOrder, cursor = cursor)
        return request<Unit, InlineResponse2003>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesGet? = null, cursor: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (startDate != null) {
                    put("start_date", listOf(startDate.toString()))
                }
                if (endDate != null) {
                    put("end_date", listOf(endDate.toString()))
                }
                if (sortOrder != null) {
                    put("sort_order", listOf(sortOrder.toString()))
                }
                if (cursor != null) {
                    put("cursor", listOf(cursor.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/operation-routes",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesIdGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null): OperationRoute {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesIdGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, id = id, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesIdGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<OperationRoute> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesIdGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, id = id, xRequestId = xRequestId)
        return request<Unit, OperationRoute>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesIdGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, id: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "id" to id,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/operation-routes/{id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesOperationRouteIdDelete(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, operationRouteId: kotlin.String, xRequestId: kotlin.String? = null): Unit {
        v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesOperationRouteIdDeleteWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, operationRouteId = operationRouteId, xRequestId = xRequestId)
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesOperationRouteIdDeleteWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, operationRouteId: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<Unit> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesOperationRouteIdDeleteRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, operationRouteId = operationRouteId, xRequestId = xRequestId)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesOperationRouteIdDeleteRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, operationRouteId: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "operation_route_id" to operationRouteId,
        )

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/operation-routes/{operation_route_id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesOperationRouteIdPatch(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, operationRouteId: kotlin.String, operationRoute: UpdateOperationRouteInput, xRequestId: kotlin.String? = null): OperationRoute {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesOperationRouteIdPatchWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, operationRouteId = operationRouteId, operationRoute = operationRoute, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesOperationRouteIdPatchWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, operationRouteId: kotlin.String, operationRoute: UpdateOperationRouteInput, xRequestId: kotlin.String? = null): ResponseEntity<OperationRoute> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesOperationRouteIdPatchRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, operationRouteId = operationRouteId, operationRoute = operationRoute, xRequestId = xRequestId)
        return request<UpdateOperationRouteInput, OperationRoute>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesOperationRouteIdPatchRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, operationRouteId: kotlin.String, operationRoute: UpdateOperationRouteInput, xRequestId: kotlin.String? = null) : RequestConfig<UpdateOperationRouteInput> {
        val localVariableBody = operationRoute
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "operation_route_id" to operationRouteId,
        )

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/operation-routes/{operation_route_id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesPost(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, operationRoute: kotlin.Any, xRequestId: kotlin.String? = null): OperationRoute {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesPostWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, operationRoute = operationRoute, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesPostWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, operationRoute: kotlin.Any, xRequestId: kotlin.String? = null): ResponseEntity<OperationRoute> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesPostRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, operationRoute = operationRoute, xRequestId = xRequestId)
        return request<kotlin.Any, OperationRoute>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdOperationRoutesPostRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, operationRoute: kotlin.Any, xRequestId: kotlin.String? = null) : RequestConfig<kotlin.Any> {
        val localVariableBody = operationRoute
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/operation-routes",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

}
