/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.apis

import com.fasterxml.jackson.annotation.JsonProperty

import org.springframework.web.client.RestClient
import org.springframework.web.client.RestClientResponseException

import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
import org.springframework.http.ResponseEntity
import org.springframework.http.MediaType


import com.midaz.client.transactions.models.Error
import com.midaz.client.transactions.models.InlineResponse2001
import com.midaz.client.transactions.models.Operation
import com.midaz.client.transactions.models.UpdateOperationInput
import com.midaz.client.transactions.infrastructure.*

class OperationsApi(client: RestClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(RestClient.builder()
        .baseUrl(baseUrl)
        .messageConverters { it.add(MappingJackson2HttpMessageConverter()) }
        .build()
    )


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdOperationsGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, accountId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: kotlin.String? = null, cursor: kotlin.String? = null, type: kotlin.String? = null): InlineResponse2001 {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdOperationsGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, accountId = accountId, xRequestId = xRequestId, limit = limit, startDate = startDate, endDate = endDate, sortOrder = sortOrder, cursor = cursor, type = type)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdOperationsGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, accountId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: kotlin.String? = null, cursor: kotlin.String? = null, type: kotlin.String? = null): ResponseEntity<InlineResponse2001> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdOperationsGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, accountId = accountId, xRequestId = xRequestId, limit = limit, startDate = startDate, endDate = endDate, sortOrder = sortOrder, cursor = cursor, type = type)
        return request<Unit, InlineResponse2001>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdOperationsGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, accountId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: kotlin.String? = null, cursor: kotlin.String? = null, type: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (startDate != null) {
                    put("start_date", listOf(startDate.toString()))
                }
                if (endDate != null) {
                    put("end_date", listOf(endDate.toString()))
                }
                if (sortOrder != null) {
                    put("sort_order", listOf(sortOrder.toString()))
                }
                if (cursor != null) {
                    put("cursor", listOf(cursor.toString()))
                }
                if (type != null) {
                    put("type", listOf(type.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "account_id" to accountId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/accounts/{account_id}/operations",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdOperationsOperationIdGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, accountId: kotlin.String, operationId: kotlin.String, xRequestId: kotlin.String? = null): Operation {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdOperationsOperationIdGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, accountId = accountId, operationId = operationId, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdOperationsOperationIdGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, accountId: kotlin.String, operationId: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<Operation> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdOperationsOperationIdGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, accountId = accountId, operationId = operationId, xRequestId = xRequestId)
        return request<Unit, Operation>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdAccountsAccountIdOperationsOperationIdGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, accountId: kotlin.String, operationId: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "account_id" to accountId,
            "operation_id" to operationId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/accounts/{account_id}/operations/{operation_id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionsTransactionIdOperationsOperationIdPatch(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionId: kotlin.String, operationId: kotlin.String, operation: UpdateOperationInput, xRequestId: kotlin.String? = null): Operation {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionsTransactionIdOperationsOperationIdPatchWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, transactionId = transactionId, operationId = operationId, operation = operation, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionsTransactionIdOperationsOperationIdPatchWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionId: kotlin.String, operationId: kotlin.String, operation: UpdateOperationInput, xRequestId: kotlin.String? = null): ResponseEntity<Operation> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionsTransactionIdOperationsOperationIdPatchRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, transactionId = transactionId, operationId = operationId, operation = operation, xRequestId = xRequestId)
        return request<UpdateOperationInput, Operation>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionsTransactionIdOperationsOperationIdPatchRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionId: kotlin.String, operationId: kotlin.String, operation: UpdateOperationInput, xRequestId: kotlin.String? = null) : RequestConfig<UpdateOperationInput> {
        val localVariableBody = operation
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "transaction_id" to transactionId,
            "operation_id" to operationId,
        )

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/transactions/{transaction_id}/operations/{operation_id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

}
