/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.midaz.client.transactions.apis

import com.fasterxml.jackson.annotation.JsonProperty

import org.springframework.web.client.RestClient
import org.springframework.web.client.RestClientResponseException

import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
import org.springframework.http.ResponseEntity
import org.springframework.http.MediaType


import com.midaz.client.transactions.models.CreateTransactionRouteInput
import com.midaz.client.transactions.models.Error
import com.midaz.client.transactions.models.InlineResponse2004
import com.midaz.client.transactions.models.TransactionRoute
import com.midaz.client.transactions.models.UpdateTransactionRouteInput
import com.midaz.client.transactions.infrastructure.*

class TransactionRouteApi(client: RestClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(RestClient.builder()
        .baseUrl(baseUrl)
        .messageConverters { it.add(MappingJackson2HttpMessageConverter()) }
        .build()
    )

    /**
     * enum for parameter sortOrder
     */
    enum class SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesGet(val value: kotlin.String) {
        @JsonProperty(value = "asc") asc("asc"),
        @JsonProperty(value = "desc") desc("desc")
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesGet? = null, cursor: kotlin.String? = null): InlineResponse2004 {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, xRequestId = xRequestId, limit = limit, startDate = startDate, endDate = endDate, sortOrder = sortOrder, cursor = cursor)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesGet? = null, cursor: kotlin.String? = null): ResponseEntity<InlineResponse2004> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, xRequestId = xRequestId, limit = limit, startDate = startDate, endDate = endDate, sortOrder = sortOrder, cursor = cursor)
        return request<Unit, InlineResponse2004>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, xRequestId: kotlin.String? = null, limit: kotlin.Int? = 10, startDate: kotlin.String? = null, endDate: kotlin.String? = null, sortOrder: SortOrderV1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesGet? = null, cursor: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (startDate != null) {
                    put("start_date", listOf(startDate.toString()))
                }
                if (endDate != null) {
                    put("end_date", listOf(endDate.toString()))
                }
                if (sortOrder != null) {
                    put("sort_order", listOf(sortOrder.toString()))
                }
                if (cursor != null) {
                    put("cursor", listOf(cursor.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/transaction-routes",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesPost(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRoute: CreateTransactionRouteInput, xRequestId: kotlin.String? = null): TransactionRoute {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesPostWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, transactionRoute = transactionRoute, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesPostWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRoute: CreateTransactionRouteInput, xRequestId: kotlin.String? = null): ResponseEntity<TransactionRoute> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesPostRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, transactionRoute = transactionRoute, xRequestId = xRequestId)
        return request<CreateTransactionRouteInput, TransactionRoute>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesPostRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRoute: CreateTransactionRouteInput, xRequestId: kotlin.String? = null) : RequestConfig<CreateTransactionRouteInput> {
        val localVariableBody = transactionRoute
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
        )

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/transaction-routes",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdDelete(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRouteId: kotlin.String, xRequestId: kotlin.String? = null): Unit {
        v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdDeleteWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, transactionRouteId = transactionRouteId, xRequestId = xRequestId)
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdDeleteWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRouteId: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<Unit> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdDeleteRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, transactionRouteId = transactionRouteId, xRequestId = xRequestId)
        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdDeleteRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRouteId: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "transaction_route_id" to transactionRouteId,
        )

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/transaction-routes/{transaction_route_id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdGet(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRouteId: kotlin.String, xRequestId: kotlin.String? = null): TransactionRoute {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdGetWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, transactionRouteId = transactionRouteId, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdGetWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRouteId: kotlin.String, xRequestId: kotlin.String? = null): ResponseEntity<TransactionRoute> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdGetRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, transactionRouteId = transactionRouteId, xRequestId = xRequestId)
        return request<Unit, TransactionRoute>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdGetRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRouteId: kotlin.String, xRequestId: kotlin.String? = null) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "transaction_route_id" to transactionRouteId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/transaction-routes/{transaction_route_id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdPatch(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRouteId: kotlin.String, transactionRoute: UpdateTransactionRouteInput, xRequestId: kotlin.String? = null): TransactionRoute {
        val result = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdPatchWithHttpInfo(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, transactionRouteId = transactionRouteId, transactionRoute = transactionRoute, xRequestId = xRequestId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdPatchWithHttpInfo(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRouteId: kotlin.String, transactionRoute: UpdateTransactionRouteInput, xRequestId: kotlin.String? = null): ResponseEntity<TransactionRoute> {
        val localVariableConfig = v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdPatchRequestConfig(authorization = authorization, organizationId = organizationId, ledgerId = ledgerId, transactionRouteId = transactionRouteId, transactionRoute = transactionRoute, xRequestId = xRequestId)
        return request<UpdateTransactionRouteInput, TransactionRoute>(
            localVariableConfig
        )
    }

    fun v1OrganizationsOrganizationIdLedgersLedgerIdTransactionRoutesTransactionRouteIdPatchRequestConfig(authorization: kotlin.String, organizationId: kotlin.String, ledgerId: kotlin.String, transactionRouteId: kotlin.String, transactionRoute: UpdateTransactionRouteInput, xRequestId: kotlin.String? = null) : RequestConfig<UpdateTransactionRouteInput> {
        val localVariableBody = transactionRoute
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        authorization.apply { localVariableHeaders["Authorization"] = this.toString() }
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "organization_id" to organizationId,
            "ledger_id" to ledgerId,
            "transaction_route_id" to transactionRouteId,
        )

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/organizations/{organization_id}/ledgers/{ledger_id}/transaction-routes/{transaction_route_id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

}
